#eureka\u670D\u52A1\u5668\u7684\u542F\u52A8\u7AEF\u53E3  
server:  
  port: 8080
    
#eureka\u7684\u4E3B\u673A\u540D \u5982\u679C\u4E0D\u914D\u7F6E \u4F1A\u4ECE\u64CD\u4F5C\u7CFB\u7EDF\u83B7\u53D6  
eureka:  
  instance:  
    hostname: mymaster  
    preferIpAddress: true  #\u672A\u914D\u7F6Ehostname\u65F6 \u4F7F\u7528\u672C\u673Aip\u5730\u5740\u4F5C\u4E3A\u4E3B\u673A\u540D ipAddress\u662Fip\u5730\u5740  
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}  
    appname: eurekaserver  #\u5E94\u7528\u7A0B\u5E8F\u7684\u540D\u79F0  
    namespace: myeureka \u5BF9\u5916\u516C\u5E03\u5730\u5740\u65F6\u7684\u547D\u540D\u7A7A\u95F4\u4E5F\u5C31\u662F\u4E0A\u4E0B\u6587\u8DEF\u5F84 \u4E0D\u8BBE\u7F6E\u9ED8\u8BA4\u4E3Aeureka  
  client:  
    registerWithEureka: false   
    fetchRegistry: false  #\u662F\u5426\u5141\u8BB8\u5BA2\u6237\u7AEF\u6293\u53D6eureka\u7684\u6CE8\u518C\u4FE1\u606F  
    serviceUrl:  
      defaultZone: http://mymaster:8761/myeureka/  
security:           
  basic:  
    enabled: true #启动认证    
  user:  
    name: jiaozi #用户名  
    password: jiaozi123 #密码 